[package]
name = "thruster-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
csv = "1"
ahash = "0.8"
serde = { version = "1", features = ["derive"] }
itertools = "0.11"

# bevy = { version = "0.12", default-features = false, features = ["animation", "bevy_asset", "bevy_gilrs", "bevy_scene", "bevy_winit", "bevy_core_pipeline", "bevy_pbr", "bevy_gltf", "bevy_render", "multi-threaded", "filesystem_watcher", "wayland", "webgl2", "tonemapping_luts", "ktx2", "zstd", "default_font", "dynamic_linking"] }
bevy = { version = "0.12", default-features = false, features = [
  "wayland",
  # "dynamic_linking",
  "animation",
  "bevy_asset",
  "bevy_gilrs",
  "bevy_scene",
  "bevy_winit",
  "bevy_core_pipeline",
  "bevy_pbr",
  "bevy_gltf",
  "bevy_render",
  "bevy_sprite",
  "bevy_text",
  "bevy_ui",
  "multi-threaded",
  "png",
  "hdr",
  "vorbis",
  "bevy_gizmos",
  "android_shared_stdcxx",
  "tonemapping_luts",
  "default_font",
  "webgl2",
] }
bevy_panorbit_camera = "0.9"
bevy_egui = "0.23"

hexasphere = "9"


motor_math = { git = "https://github.com/Eoghanmc22/mate-rov-2024.git" }


[profile.release]
debug = true

[profile.release-lto]
inherits = "release"
lto = true
codegen-units = 1
debug = false

[profile.web]
inherits = "release"
lto = true
codegen-units = 1
opt-level = 's'
debug = false
